name: Python tests

on:
  push:
    paths:
      - "resotool/*"
  pull_request:
    paths:
      - "resotool/*"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Install and start Redis
      run: |
        sudo apt-get install redis-server
        sudo systemctl start redis-server.service
    - name: Install Python dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry install
    - name: Run Tests
      run: |
        cd resotool
        make test
